sudo: required
language: go
services:
 - docker

install:
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-ce
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - docker build -t github-version-checker .
  - gometalinter ./...

notifications:
  email: false